### ISSUE TITLE
Step Memory Exceeded errors: too heavy memory usage

### ISSUE THREAD

**Issue by NLSVTN** [ficusss/PyGMNormalize#1]
In the `utils.py` the last line (or possibly some other line in TMM algorithm) uses too much memory which prevents me from running the function on most of the RNAseq datasets on the cluster even with rather large memory available (200Gb).
It needs to be rewritten somehow to improve the situation. 

Also asked on stackoverflow:

https://stackoverflow.com/questions/52266003/reduce-memory-usage-of-a-line-of-code-that-uses-numpy

**Comment by ficusss** [comment]
Thank you for your comment.
Has corrected.
You can activate the RAM-saving mode in your code.
For this, when calling functions, set the parameter saving_memory = True (default False)
Please test on your data.

**Comment by NLSVTN** [comment]
Cool, thank you!

On 18 September 2018 at 19:13, Григорий Феоктистов <notifications@github.com
